# Conclusion

In conclusion, this study shows that the likelihood of a Sharknado occurring is very low. By comparing the weight of a great white shark to different car types of similar weight, there is a way to determine the strength of a tornado on the EF (Enhanced Fujita) Scale, able to pick up a car (or a great white shark of similar weight). The EF rating required for this to happen is an EF3-EF5 tornado. This range of tornado strength has wind speeds of 136 mph to 200+ mph. For a Sharknado to happen, tornadoes of this strength need to happen where great white sharks are. Florida, South Carolina, Virginia, Califorina, and Los Angeles, California (chosen because it's the setting of the Sharknado movie) are coastal places. Oklahoma was also chosen to compare the amount and EF scale types with the other places mentioned. This study looks at tornado data from 2015-2026 and their strength from the EF scale.

Florida, South Carolina, and Virginia have very few tornadoes with the desired strength to be able to pick up great white sharks. Florida had just five tornadoes with an EF3 scale rating, South Carolina had nine EF3 tornadoes and one EF4 tornado, while Virginia had just five EF3 scale rating like Florida. These tornadoes all happened inland, so the possibility of picking up a great white shark is very unlikely. California and Los Angeles, California have had no tornadoes of strength EF3 or higher in the last 10 years. There will not be another Sharknado hitting LA again.

Even though Oklahoma has had many tornadoes strong enough (EF3 to EF5) to be able to pick up a great white shark over the last 10 years, there are no great whites in Oklahoma. The most likely scenario to make a Sharknado inland is having an EF3-EF5 tornado destroy an aquarium in inland places where strong enough tornadoes occur. Even then, this event is not very likely.

Overall, the insurance payouts for property damage from the event of a Sharknado are extremely unlikely, if not a zero percent chance. Tornadoes and strong storms will continue to exist, which is still a concern for property damage purposes.
