---
title: "Draft: Data Documentation"
---


::: callout-note

Put your name on your work and give it an appropriate title -- edit your _quarto.yml file

This needs to be in paragraph format (notes are fine in the draft, but for the real thing, please format everything and connect things with words.)


Make sure you add a date -- the release date? -- to your bibliography entry, and make sure the other fields are filled in. Zotero doesn't always catch everything perfectly.

:::

-   Goal is to give evidence to my boss that shark-infested storms are very rare, if not impossible.
-   The data I found is from the NOAA data base. I extracted tornado data from Los Angeles (the setting of Sharknado), Florida (tropical storms are abundant), South Carolina (another more tropical place), and Oklahoma (the tornado capitol of the nation).
-   All the data sets are the same format. They were collected from the same data base NOAA.gov.
-   These are the important aspects of the data sets collected
    -   County Location
    -   Begin Location
    -   Begin Date
    -   Begin Time
    -   Tornado F Scale
    -   Direct Deaths
    -   Direct Injuries
    -   Property Damage
    -   Tornado Length and Width
    -   End Location
    -   End Date
    -   End Time
-   Measurements are take by the MWS Storm Survey, Spotters, State officials and the Public

Florida tornado data: @StormEventsDatabase

South Carolina tornado data: @StormEventsDatabasea

Oklahoma tornado data: @StormEventsDatabaseb

Los Angeles tornado data: @StormEventsDatabasec

-   For a tornado to lift up a Shark I compared the weight of a Great White Shark to a normal cars weight
    -   Great White Shark Weight
        -   NOAA Says up to 4,500 lbs
    -   Car weight
        -   According to autoinsurance.com a Car SUV is 3,986 lbs
        -   According to autoinsurance.com a Truck SUV is 4,578 lbs
    -   Great White Sharks and Car SUVs and Truck SUVs weigh relatively around the same weight.
-   oteroadjusting.com says EF3 tornadoes are likely to toss cars and trucks and EF5 can "almost certainly lift and destroy cars."
-   I will use this as a reference to say that EF3-EF5 tornadoes will be able to lift a great white shark.

Great White Shark Info: @fisheries_white_2025

How much does a car weigh: @noauthor_how_nodate

Can a car be picked up by a tornado: @noauthor_can_2025


::: callout-note

These are fine (other than the author being missing), but you need to incorporate them into your writing as an organic part of the paragraphs.

:::
