# Methods

A Sharknado event involves a tornado being able to lift a great white shark out of the ocean and carry it onto land. To see if this is possible, we need to look at the physics: the weight of a great white shark, what objects are known to be picked up by tornadoes, and the magnitude of tornadoes required to pick up a shark. First, finding out how a great white shark could be picked up by a tornado is nessesary. The weight of a great white shark will be compared to other objects that can and have been picked up by tornadoes, such as cars. Next, figuring out what strength (in EF scale from EF3 - EF5) of a tornado would be needed to be able to lift a great white shark and a car. Lastly, identifying tornadoes from 2015-2026 that are in that EF range from 6 different places in the United States. These places are be Florida, South Carolina, Virginia, Oklahoma, California, and Los Angeles. These places were chosen for specific reasons. Florida has many tropical storms and is a coastal state (Florida, [-@StormEventsDatabaseFL]). South Carolina is also another place that can be hit by tropical storms and is another coastal state (South Carolina, [-@StormEventsDatabaseSC]). Virginia is a coastal state that has had a good amount of tornadoes of our criteria (Virginia, [-@StormEventsDatabaseVA]). Oklahoma is not a coastal state, but it is the tornado capital of the United States, so we will just look at the number of tornadoes that meet the criteria to get an idea of how rare strong tornadoes are (Oklahoma, [-@StormEventsDatabaseOK]). California ([-@StormEventsDatabaseCA]) was chosen because it is the state setting of Sharknado, while Los Angeles ([-@StormEventsDatabaseLA]) was picked because it is the city setting of the Sharknado movie (@SharknadoTVMovie).

Sharks and cars weigh relatively the same in pounds (lbs). The average great white shark weighs around 4,500 lbs (@fisheries_white_2025). A car SUV weighs around 3,986 lbs while a truck SUV weighs around 4,578 lbs (@noauthor_how_nodate). This means that your average great white shark weighs more than a big car and as much as a truck or SUV. We will use a car as the base to find what EF scale level will be used to lift a great white shark out of the water.

The EF scale is made up of 6 different ratings of tornado based on 3-second wind speed in mph (@us_department_of_commerce_enhanced_nodate). An EF0 tornado has the lowest wind speed, ranging between 65-85 mph, EF1 has wind speeds between 86-110 mph, EF2 has wind speeds between 111-135 mph, EF3 has wind speeds of 136-165 mph, EF4 has speeds between 166-200 mph, and EF5 has wind speeds that are over 200 mph. An EF3 tornado is likely to toss cars and trucks, while an EF4 is very likely to toss cars many feet, and an EF5 tornado is almost certain to lift and destroy cars. EF3 tornadoes are unlikely to fully pick up a shark but it is still important to analyze them because a great white shark could be moved by an EF3 tornado. Because of the comparison of a great white shark to the size and weight of a car SUV, and a truck SUV, that gives a good comparison to be able to put a shark in the place of such cars in the EF scales' ability to lift cars (@quach_can_2025). Tornadoes from EF3 to EF5 are chosen because this is the strength of tornadoes that are able to lift a car (@salaita_how_nodate).

Using these metrics, finding storms that have had the potential to produce a Sharknado allows the ability to evaluate the potential insurance risk with such events.